language: node_js
node_js:
- node
cache:
  directories:
    - node_modules
jobs:
  include:
    - stage: "setup"
      name: "Pre-Setup"
      script: npm install -g serverless yarn
    - name: "Install Dependency"
      script: yarn install
    - stage: "deploy"
      name: "Deploy to AWS Lambda"
      script: sls deploy
stages:
  - setup
  - name: deploy
    if: branch = master