language: node_js
node_js:
- node
cache:
  directories:
    - node_modules
branches:
  only:
  - develop
  - master
jobs:
  include:
    - stage: setup
      name: 'Install Dependency'
      script: yarn install
    - stage: test
      name: 'Eslint'
      script: yarn lint-js
    - stage: deploy
      name: 'Deploy to AWS Lambda'
      script: sls deploy
notifications:
  slack: amway-5hs5654:WbTqYUgqcHFRvkpo4JnvtUbb