language: node_js
node_js:
- node
cache:
  directories:
    - node_modules
jobs:
  include:
    - stage: setup
      name: 'Install Dependency'
      script: yarn install
    - name: Set prod environment parameters
      if: branch = master
      env:
        - FOO=foo1
        - BOO=boo1
      script: echo "done"
    - name: Set develop environment parameters
      if: branch = develop
      env:
        - FOO=foo2
        - BOO=boo2
      script: echo "done"
    - stage: test
      name: 'Eslint'
      script: yarn lint-js
    - stage: deploy
      name: 'Deploy to AWS Lambda'
      script: sls deploy
notifications:
  slack: amway-5hs5654:WbTqYUgqcHFRvkpo4JnvtUbb