language: node_js
node_js:
- node
cache:
  directories:
    - node_modules
jobs:
  include:
    - stage: set prod environment parameters
      if: branch = master
      env: FOO=foo1
    - stage: set develop environment parameters
      if: branch = develop
      env: FOO=foo2
    - stage: setup
      name: 'Install Dependency'
      script: yarn install
    - stage: test
      name: 'Eslint'
      script: yarn lint-js
    - stage: deploy
      name: 'Deploy to AWS Lambda'
      script: sls deploy
notifications:
  slack: amway-5hs5654:WbTqYUgqcHFRvkpo4JnvtUbb